env: flex
runtime: php
runtime_config:
  document_root: web

env_variables:
  NGINX_CONF_INCLUDE: config/nginx-app.conf
  PHP_INI_OVERRIDE: config/php-app.ini
# [END overrides]

beta_settings:
   cloud_sql_instances: bookstore-177621:us-central1:bookstore
